name: hps_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/EBGaramond-VariableFont_wght.ttf
